# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/marketplace_opportunity_scraper/all/marketplace_opportunity_scraper.rbi
#
# marketplace_opportunity_scraper-0.1.1
module MarketplaceOpportunityScraper
end
module MarketplaceOpportunityScraper::Utils
  def build_url(type, status); end
  def check_params(param, type); end
  def check_status(status); end
  def check_type(type); end
  def date_from_label(page, label); end
  def find_by_label(page, label); end
  def text_from_label(page, label); end
  def valid_statuses; end
  def valid_types; end
end
class MarketplaceOpportunityScraper::Opportunity
  def awarded_to; end
  def banner; end
  def budget; end
  def buyer; end
  def closing; end
  def description; end
  def expected_start_date; end
  def find_by_label(label); end
  def id; end
  def initialize(attrs); end
  def location; end
  def page; end
  def published; end
  def question_deadline; end
  def self.all(type: nil, status: nil); end
  def self.find(id); end
  def self.mechanize; end
  def self.opportunity_from_id(id); end
  def self.opportunity_from_search_result(element); end
  def skills; end
  def status; end
  def text_from_label(label); end
  def title; end
  def url; end
  extend MarketplaceOpportunityScraper::Utils
end
