# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_13; end
module ::Anonymous_Delegator_8; end
module ::Anonymous_Delegator_9; end
module ActiveSupport::ActionController::Base; end
